language: python

dist: bionic          # required for Python >= 3.7
python: 3.7           
sudo: required
addons:
  apt:
    update: true

install: 
  - pip install --upgrade pip  
  - pip install -r requirements.txt
  - pip install ./python/.

script: 
  - pytest ./python/test/
  - rrsg_cgreco --datafile ./python/rrsg_cgreco/rawdata_brain_radial_96proj_12ch.h5 --config ./python/rrsg_cgrecp/default.txt
